version: '2'
services:
    ebook-app:
        image: ebook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=ebook-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    ebook-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: ebook-cassandra
    ebook-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=ebook-cassandra
    ebook-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: ebook-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
